# This creates the demonstration utility "lguest" which runs a Linux guest.
CFLAGS:=-m32 -g -Wall -Wmissing-declarations -Wmissing-prototypes -O3 -U_FORTIFY_SOURCE -pthread

all: lguest

clean:
	rm -f lguest
